### ISSUE TITLE
图片裁剪处理

### ISSUE THREAD

**Issue by lgGuo** [qingmei2/RxImagePicker#1]
建议加上图片裁剪功能

**Comment by qingmei2** [comment]
@lgGuo 

已收到您的建议:smile:。

图片裁剪是我考虑过的，相比图片选择器，我个人认为 **图片的调整** 对于 RxImagePicker 应该是额外的UI拓展功能。

我用 **额外的** 形容它，是因为它严格来说，是应该放在基础组件中的（即使是打开系统的相册或者拍照，它也应该提供给开发者一个图片裁剪的接口以供选择），同时，因为它也涉及到自定义UI界面（或者说UI对这个功能更重要），放在UI的支持包中似乎也不错。

同时， **图片的调整（除了裁剪之外，还有图片压缩，涂鸦，注释，模糊处理等）** 是一个大的功能，我认为它也应该有一个复杂的设计来实现。单纯的写一个固定的界面实现图片的裁剪或者压缩并不是很困难，但是这会带来耦合，这不是我希望看到的。

我很感谢您能提出这样一个优秀的issue :thumbsup: ，给我了一个阐述自己思路的机会。我认为这个功能是有用的，我会尝试 调整目前的架构，并增加一个Optional的support库 以支持 RxImagePicker实现图片调整的功能，但也许需要一些时间:fist:。

如果您有更好的idea，欢迎一起探讨。
