### ISSUE TITLE
取消拍照，如何处理的呢

### ISSUE THREAD

**Issue by Ksy007** [qingmei2/RxImagePicker#11]
进入拍照界面，如果用户突然不想拍了，直接返回，现在好像会直接返回更上一级的页面，即显示拍照dialog所在页面的上一级页面，请问我该如何处理呢

**Comment by qingmei2** [comment]
@Ksy007 

你好，目前的拍照功能，实际上是通过上下文打开系统的Camera进行拍照，并将拍照的结果返回给上一个界面。

> 直接返回更上一级的页面，即显示拍照dialog所在页面的上一级页面

您能详细描述一下吗？我没有太理解您遇到的情况。

**Comment by Ksy007** [comment]
简单来说，就是用户已经吊起拍照的页面，但是突然不想拍了，好像没有取消键，直接按系统返回键，会等待一会儿，直接返回A页面，前面的操作：A到B，B页面是dialog吊起拍照的地方
