### ISSUE TITLE
有没有打算加入裁剪，压缩功能？

### ISSUE THREAD

**Issue by le9527** [qingmei2/RxImagePicker#12]
如题，基本上引用图库的地方都是为了上传图片，几乎都会涉及到裁剪和压缩，作者大神有没有考虑加入这些功能，可以像知乎和微信样式似的独立出来，还有就是应该添加一个是否显示gif的属性，这样引用起来更方便一点，不用自己去引用module改代码了

**Comment by qingmei2** [comment]
@le9527 

您好，感谢您的建议！

从大家的需求来看，图片编辑（裁剪，旋转，涂鸦，压缩）等等确实是一个迫在眉睫的需求，我最近准备在简单修改完bug之后，尝试新建一个仓库，为图片编辑的功能独立一个单独的库，但是可能会需要一些时间。

请参考 #4  和 #1
