### ISSUE TITLE
返回多张图片API

### ISSUE THREAD

**Issue by Vicent9920** [qingmei2/RxImagePicker#14]
你好，我看了一下你的文档和demo，不知道返回多张图片应该使用什么方法（我自身对RXjava不熟悉）？能不能在文档或者demo中注明，帮助一些基础比较弱的童鞋呢？

**Comment by qingmei2** [comment]
@Vicent9920 

感谢您使用RxImagePicker! 👍 

所有选中图片的Uri都已经通过流的方式 依次在onNext(Uri uri)的回调中返回了，Sample的效果是展示 **最后一个选中的图片**。

最简单获取List的方式就是您可以通过toList()操作符 **将数据流中所有的Uri汇聚成一个List**：

![image](https://user-images.githubusercontent.com/21142152/40911314-18a00c7c-6821-11e8-87d3-0aeedf70534b.png)

> **能不能在文档或者demo中注明，帮助一些基础比较弱的童鞋呢**

这是一个很好的建议，我将在最近一次的更新中更新文档。

**Comment by Vicent9920** [comment]
谢谢，我试一下
