### ISSUE TITLE
选择多张图片调用方式

### ISSUE THREAD

**Issue by Vicent9920** [qingmei2/RxImagePicker#15]
在选择多张图片时，第二次选择的时候能不能传入上一次已经选择的图片呢？我阅读了文档和查看了一下源码，没有找到相关的内容。

**Comment by qingmei2** [comment]
@Vicent9920 

感谢您宝贵的建议！ 👍 

> 第二次选择的时候能不能传入上一次已经选择的图片呢

关于这个需求，您能够提供一个生产中的 **实际场景** 吗?

我的第一感觉是，这个需求可以在support_zhihu或者support_wechat中 通过拓展的方式，新加一个类，然后持有上一次 选择结果List的引用，然后在图片选择界面中，添加对其处理的逻辑。

希望您能对于这个需求的实现提供更多的细节:smile:

**Comment by Vicent9920** [comment]
应用情景类似于朋友圈，当我选中了四张图片后，我打算删除第三张，并且再增加两张，这时候进入相册就只能重新选择，并不能保存之前的图片引用。
至于自己扩展，我想说的是我使用的是微信的相关主题，但是在RxImagePicker.Builder 的配置类以及DefaultImagePicker 都没有看见相关实现的内容，因此才留言请教的！

**Comment by qingmei2** [comment]
@Vicent9920 

这是一个很常见的需求，我的思路是 **之前选中的图片** 由Activity(或者其他容器)持有一个List，并存储它们，以作为图片列表的 **数据源** ；

每次图片选择结束后，将选择结果的selectResult 反映到 **数据源list** 上（考虑最简单的情况，就是list.addAll(selectResult),然后通过norifyDataChanged **将数据源的改变反映到UI上**），这也许是一个不错的处理方式——当然，原因是我不需要改代码了2333  🐶

**Comment by Vicent9920** [comment]
你这个思路我知道，但是其中有几个**问题**：

1. 数据重复，已经选择的图片不能**自动去重**
2. 与微信朋友圈选择的模式差别挺大，前者可选中的图片**数量**始终有**控制**，后者是在容器中累加，会给用户造成一种错觉：我不是只能选9张吗？为什么我选了中8张之后还能选中9张？

**Comment by qingmei2** [comment]
@Vicent9920 

了解，Rxjava的 **filter** 操作符也许能解决问题1， **将已选的图片反映到图片选择的UI上** 是一个不错的建议。 

这个需求确实没有考虑到，我会考虑在接下来的处理中加上 **Filter** 类型的处理方式，处理方式也许会像 **Retrofit** 接口方法中的参数类似，通过参数注入交给库去处理。

**Comment by mallxiaodoudou** [comment]
我问个上面的问题  已经选择完2张图片了，再次进入相册需要自动勾选上次选的那2张图片，我看了作者的解决方案也下载demo查看了下，没有一个明确的解决办法，是在注解上加 ，还是在Build中添加指定的参数？

**Comment by qingmei2** [comment]
@liukai2530533 

目前库本身还不支持这个功能

**Comment by qingmei2** [comment]
因为个人精力有限，该功能暂不考虑，有兴趣的朋友可以自行修改源码并提交PR哈

🤝
