### ISSUE TITLE
项目中没用到Rxjava、dragger，并不是很想引入这两个库，要不然打算换作者这个图片库的。要是作者有时间可以考虑出个非rxjava版的

### ISSUE THREAD

**Issue by linxingxi** [qingmei2/RxImagePicker#16]

**Comment by qingmei2** [comment]
@linxingxi 

感谢您的建议！

有贬低其他库之嫌，事实上，Github上基本上所有主流的图片选择器库，我都研究了一遍，它们其中相当多的依赖更为严重，但他们没有罗列出来而已（Matisse算是例外， ❤️ 它）......

> 有时间可以考虑出个非rxjava版的

我会考虑，但优先级可能不会很高，但我可能会尝试在之后的一次大版本中，移除dagger2。

如果您有兴趣贡献源码，非常欢迎您提交PR 😄
