### ISSUE TITLE
图片加载器可否让开发者自行配置呢？

### ISSUE THREAD

**Issue by y1xian** [qingmei2/RxImagePicker#19]
有些老项目用的glide3.+ ,而你的是4.5 这样对老项目就不友好了

**Comment by qingmei2** [comment]
目前的项目就是通过自定义加载器进行加载。

请参考[WechatConfigrationBuilder这个类](https://github.com/qingmei2/RxImagePicker/blob/master/rximagepicker_support_wechat/src/main/java/com/qingmei2/rximagepicker_extension_wechat/WechatConfigrationBuilder.java)，它本身就提供了配置图片加载引擎的接口。

![image](https://user-images.githubusercontent.com/21142152/41400042-8fa6228c-6fee-11e8-94ae-fd551cde2551.png)

**Comment by y1xian** [comment]
嗯，好的
