### ISSUE TITLE
图片加载框架

### ISSUE THREAD

**Issue by lgGuo** [qingmei2/RxImagePicker#2]
图片加载框架建议可以动态配置

**Comment by qingmei2** [comment]
@lgGuo 

感谢您宝贵的建议！

目前的知乎主题和微信主题的拓展UI支持是支持 **动态配置图片加载框架** 的,通过对对应主题的**ConfigrationBuilder** 提供的imageEngine() API进行对应的拓展即可：

![image](https://user-images.githubusercontent.com/21142152/39733272-8a29b6dc-52a4-11e8-9ecc-1593d86297e7.png)

RxImagePicker默认使用了V4版本的Glide作为默认的图片加载引擎：

![image](https://user-images.githubusercontent.com/21142152/39733347-e67b7100-52a4-11e8-8a4c-08b118fc87df.png)

当然，如果您的项目中使用到了其它的图片加载框架，可以通过实现 support下提供的 **ImageEngine**接口，然后自定义您的UI加载引擎。

**目前我正在整理RxImagePicker的wiki和README，这可能需要一些时间才能放出 RxImagePicker 的详细使用文档，还望见谅！**
