### ISSUE TITLE
拍照的问题

### ISSUE THREAD

**Issue by NerdAnonymous** [qingmei2/RxImagePicker#20]
关于拍照使用系统相机问题，在重写了onActivityResult的Activity中使用openCamer，由于BaseSystemPickerView中的Fragment重写了onActivityResult，使得fragmen中的onActivityResult和调用者中的onActivityResult发生冲突，不回调，造成拍照无反应的问题

**Comment by qingmei2** [comment]
这是Android系统设计的机制，和库本身关系不大。

这个问题的解决方案就是 **处理好Activity和Fragment之间的onActivityResult 冲突**，比如：

请不要在调用的Activity的 onActivityResult方法中第一行加上 super.onActivityResult()的调用。

如果还解决不了这个问题，能否麻烦您提供真实的代码呢？

**Comment by qingmei2** [comment]
因为长时间未回复，关闭此issue
