### ISSUE TITLE
下了demo很棒，但是我项目里添加依赖就失败了

### ISSUE THREAD

**Issue by abcdisgreat** [qingmei2/RxImagePicker#21]
直接依赖的时候报错，网上查也没找到原因
Error:Module 'com.github.qingmei2:rximagepicker:0.4.0' depends on one or more Android Libraries but is a jar

**Comment by qingmei2** [comment]
原因在于包的重复依赖，能否提供您实际项目中 v7包和v4包的版本呢？

#13  这个issue中也许会给您一些帮助。

**Comment by abcdisgreat** [comment]
@qingmei2 我用gradle版本2.2.2，support27.1.0，glide用的4.7.1,编译不了

**Comment by qingmei2** [comment]
@abcdisgreat

**Comment by abcdisgreat** [comment]
aar 我试过不行直接报错，本来打算把代码抽出来试试的，但是那个dagger注解没用过很难受

**Comment by qingmei2** [comment]
@abcdisgreat 

谢谢您的回复，是否方便把您gradle的依赖发出来呢？

**Comment by abcdisgreat** [comment]
@qingmei2 您好，刚又试了下，不知道你提供的依赖怎么回事，我用JitPack生成了一个依赖可以正常编译了
com.github.qingmei2.RxImagePicker:rximagepicker:v0.4.0

**Comment by abcdisgreat** [comment]
还有我想问下demo里选择列表中能设置只显示图片类型或只显示视频类型吗，现在好像全都显示了

**Comment by qingmei2** [comment]
@13kmsteady 👍

感谢@abcdisgreat ，能够这么久之后提出反馈，最近，我也在尝试调查 **添加依赖发生错误的问题**。

> 我用JitPack生成了一个依赖可以正常编译了

在github上release版本时，JitPack默认会自动编译项目，并生成JitPack最新的依赖，但是它的问题是，没有配置，默认生成的依赖，包括了所有的module:

```groovy
compile 'com.github.qingmei2.RxImagePicker:rximagepicker:v0.4.0'
```

这个compile依赖实际上包含了下面四个依赖：

![image](https://user-images.githubusercontent.com/21142152/42070306-552f49c6-7b88-11e8-9413-c49eaafa982e.png)

我认为，通过maven，也就是readme中提供的依赖方式，以避免多余依赖的发生，导致app体积变大更合理一些。

**Comment by abcdisgreat** [comment]
@qingmei2 demo里我手机里的部分图片不加载的情况（可能图片格式不对也可能和手机云相册有关）,能添加过滤让出现错误的图片显示特定的占位图并无法选择吗
![image](https://user-images.githubusercontent.com/33865977/42070137-9792d090-7b87-11e8-89ed-8850e03c1e24.png)

**Comment by qingmei2** [comment]
> 1.让出现错误的图片显示特定的占位图  
2.无法选择 

问题1.有两种方式：

1.简单的，自定义一个图片加载引擎,将placeHolder写死，传入一个自己项目的drawable：

![image](https://user-images.githubusercontent.com/21142152/42072474-3c7ffcee-7b93-11e8-8623-2d0de0e73c64.png)

2.修改源码中的style：

![e87c4c29-d090-4113-b606-54af4896a0a3](https://user-images.githubusercontent.com/21142152/42072512-775c12da-7b93-11e8-95cb-279771dc10c2.png)

问题2，让图片无法选择

我的理解是，让格式不正确的图片无法被点击。

目前微信，支付宝，知识星球，手Q轻聊，网易邮箱，网易云音乐，简书 都可以点击，我猜测原因是因为，CursorAdapter获取所有Media资源，是无法获知 这个资源的格式 能不能被正确识别的，所以无法做出判断。
