### ISSUE TITLE
添加依赖的时候报错

### ISSUE THREAD

**Issue by zhaoyangxihui** [qingmei2/RxImagePicker#23]
Error:Module 'com.github.qingmei2:rximagepicker:0.4.0' depends on one or more Android Libraries but is a jar

**Comment by zhaoyangxihui** [comment]
是不是跟些依赖有冲突

**Comment by qingmei2** [comment]
@zhaoyangxihui 

你看看这样能不能解决你的问题：

https://www.jianshu.com/p/f5a16b8ef271

**Comment by qingmei2** [comment]
长时间未回复，close issue
