### ISSUE TITLE
为什么不直接返回图片的路径，例如/storage/emulated/0/Pictures/1531981817827.jpg

### ISSUE THREAD

**Issue by yuzhiqiang1993** [qingmei2/RxImagePicker#24]
目前的返回结果是uri，需要自己转成path，感觉平时项目中还是用路径的比较多。

**Comment by qingmei2** [comment]
Android系统默认选择图片，返回值的类型为Uri，Uri允许用户对任何的资源通过特定的协议进行交互操作，这是通用的，此外，Glide也提供了Uri的支持，我认为Uri对于资源的标识更通用一些，如果需要path，只需要Uri.getPath()，或者进行其他处理即可。
