### ISSUE TITLE
引入项目无法编译

### ISSUE THREAD

**Issue by tdxtxt** [qingmei2/RxImagePicker#26]
错误日志：Dex cannot parse version 52 byte code.

由于你的jar包是基于jdk 1.8的，但我项目AS使用的jdk是1.7的，若要升级本地，会导致项目很多遗留问题，所以无法使用的的库。
能否解决一下？

**Comment by qingmei2** [comment]
@tdxtxt 

请问您的AndroidStudio版本多少？

**Comment by qingmei2** [comment]
长时间未回复，关闭issue
