### ISSUE TITLE
doFilter的使用?

### ISSUE THREAD

**Issue by oarage** [qingmei2/RxImagePicker#27]
调用微信图片选择后,里面有视频和图片,我怎么设置只显示图片或只显示视频?
是使用doFilter吗?这个怎么使用啊?
                        .addFilter(object : Filter() {
                                    override fun filter(context: Context, item: Item): IncapableCause {
                                        return IncapableCause("123456")
                                    }

                                    override fun constraintTypes(): Set<MimeType> {
                                        val set = HashSet<MimeType>()
                                        set.add(MimeType.JPEG)
                                        set.add(MimeType.PNG)
                                        return set
                                    }
                                })
我这样做,感觉没有用

**Comment by qingmei2** [comment]
@oarage 

请参考 #21

**Comment by qingmei2** [comment]
再引用一下 @13kmsteady 的回复吧

这里以 wechat 主题为例，当我们在初始化 RxImagePicker 时，会调用以下代码:

```Java
private void initRxImagePicker() {
        rxImagePicker = new RxImagePicker.Builder()
                .with(this)
                .addCustomGallery(
                        WechatImagePicker.KEY_WECHAT_PICKER_ACTIVITY,
                        WechatImagePickerActivity.class,
                        new WechatConfigrationBuilder(MimeType.ofImage(), false)
                                .showSingleMediaType(true) // 是否显示单类型
                                .maxSelectable(9)
                                .countable(true)
                                .spanCount(4)
                                .countable(false)
                                .theme(R.style.Wechat)
                                .build()
                )
                .build()
                .create(WechatImagePicker.class);
    }
```
当我们在创建 WechatConfigrationBuilder 对象时，传入的参数是：MimeType.ofImage()。

在 RxImagePicker 的扩展库中，提供了有 ofAll，ofImage，ofVideo 选择。

如果想选择只显示图片，指定 MimeType.ofImage，再加上 showSingleMediaType(true) 即可。

注意：如果不添加 showSingleMediaType(true)，显示单类型是不起作用的。

**Comment by oarage** [comment]
哦,知道了,谢谢
那这个filter是做什么用的呢?

**Comment by qingmei2** [comment]
API移植于Matisse，这里有一篇讲解，你可以参考下：

https://blog.csdn.net/qiaoshi96_bk/article/details/76164913

**Comment by oarage** [comment]
我新建项目,使用非常爽,但在老项目上添加,只添加基础架构,就编译不通过

../../../../../.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.0.aar/923d0767aaae1664434c89852872b640/res/values-v26/values-v26.xml |  
-- | --
error: resource android:attr/colorError not found. |  
error: resource android:attr/colorError not found. |  
error: style attribute 'android:attr/keyboardNavigationCluster' not found. |  
../../../../../.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.0.aar/923d0767aaae1664434c89852872b640/res/values/values.xml |  
error: resource android:attr/fontStyle not found. |  
error: resource android:attr/font not found. |  
error: resource android:attr/fontWeight not found. |  


说是资源找不到了,

**Comment by qingmei2** [comment]
@oarage 

我很重视这个问题，您能加入QQ群 391638630 一起探讨吗？

**Comment by oarage** [comment]
不好意思,我刚才写错了,这个问题解决了,
我exclude的module写错了,应该是appcompat-v7,我没有写"-v7"
正确的应该是:
implementation 'com.github.qingmei2:rximagepicker:2.1.2',{
        exclude group: 'com.android.support', module: 'appcompat-v7'
    }

**Comment by qingmei2** [comment]
👍 感谢你的指出，这将会给后来的开发者带来更多的借鉴，那我就关闭issue了。
