### ISSUE TITLE
studio 3.0.1 无法编译代码

### ISSUE THREAD

**Issue by tianshaokai** [qingmei2/RxImagePicker#29]
![image](https://user-images.githubusercontent.com/6706496/43674958-254d0c78-980e-11e8-8aff-2a710eb1f5cc.png)
一直从jcenter 下载，kotlin是不是有问题，我发现并没有提示更新

**Comment by qingmei2** [comment]
@tianshaokai 

是sample无法编译运行，还是自己项目中添加依赖编译不成功？

开发环境默认是最新稳定版本的AndroidStudio，目前是3.1.3，如果是sample运行不成功，请尝试升级您的AS或者本地修改依赖配置

**Comment by qingmei2** [comment]
配置还有问题，或者您觉得issue不方便即时交流，请加QQ群391638630哈

**Comment by qingmei2** [comment]
长时间未回复，close issue.

**Comment by tianshaokai** [comment]
这个我其实在群里 已经说了解决方案了，就是 google() 要放到 jcenter() 之上就可以了
