### ISSUE TITLE
为何第一点击button显示选择的图片，第二次点击这个button无任何响应？

### ISSUE THREAD

**Issue by davidhuang24** [qingmei2/RxImagePicker#3]
这是源码，谢谢

public class MainActivity extends AppCompatActivity implements View.OnClickListener ,MyImagePicker{
    private Button btn_picker;
    private ImageView iv_show;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        (btn_picker=(Button) findViewById(R.id.btn_picker)).setOnClickListener(this);
        iv_show=(ImageView) findViewById(R.id.iv_show_img);
    }

    @Override
    public void onClick(View v) {
        if(v.getId()==R.id.btn_picker){
            new RxImagePicker.Builder()
                    .with(this)
                    .build()
                    .create(MyImagePicker.class)  
                    .openGallery()            
                    .subscribe(new Consumer<File>() {
                        @Override
                        public void accept(File file) throws Exception {
                            // do what you want to do
                            Glide.with(MainActivity.this)
                                    .load(file)
                                    .into(iv_show);
                        }
                    });
        }
    }

    @Override
    public Observable<File> openGallery() {
        return null;
    }

    @Override
    public Observable<Bitmap> openCamera() {
        return null;
    }
}

**Comment by davidhuang24** [comment]
用您SystemActivity.java里的代码没问题

**Comment by qingmei2** [comment]
@davidhuang24 

感谢您选择使用RxImagePicker:thumbsup:

[RxImagePicker](https://github.com/qingmei2/RxImagePicker) 底层通过使用 **动态代理** 生成 MyImagePicker 接口的对象，因此您不需要让 Activity 实现 **MyImagePicker** 接口。

您只需要将MyImagePicker.class 作为参数，传给 RxImagePicker.Builder，框架会 **自动生成** MyImagePicker的对象，比如，您在您的Activity的onCreate()方法中初始化MyImagePikcer:

```
MyImagePicker imagePicker = new RxImagePicker.Builder()
                .with(this)
                .build()
                .create(MyImagePicker.class);
```

这之后，如果您想打开相册，只需要像您代码写的一样：

```
@Override
public void onClick(View v) {
      imagePicker.openGallery()            
                .subscribe(new Consumer<File>() {
                    @Override
                    public void accept(File file) throws Exception {
                        Glide.with(MainActivity.this) .load(file).into(iv_show);
                    }
                });
}
```

为什么imagePicker.openGallery()  就能够知道我是想要打开相册呢，因为通过注解，您已经将您这个方法想做的事告诉了 [RxImagePicker框架](https://github.com/qingmei2/RxImagePicker)：

```
public interface MyImagePicker {

    @Gallery    //给这个方法加上这个注解，就是告诉框架您想要打开相册选择图片
    @AsFile     //返回值为File类型
    Observable<File> openGallery();

}
```

请您参考sample再次尝试，如果有疑问欢迎在本issue中提出 😄.

**Comment by davidhuang24** [comment]
非常感谢这么有心的作者
