### ISSUE TITLE
Espresso为什么用不了

### ISSUE THREAD

**Issue by djh2717** [qingmei2/RxImagePicker#31]
楼主,我想问下我照你说的那样加了依赖包,然后创建了一个测试代码,在AndroidTest 目录下,但是为什么就是没有 onView方法,模拟不了点击事件...很无奈..希望能得到您的答复,谢谢!

**Comment by qingmei2** [comment]
@djh2717 

请问你能够运行sample中的测试代码吗？

如果本项目的测试代码能运行，而个人项目不可以，应该是项目的配置原因。

能否加入这个QQ群呢,391638630, 更方便交流。

**Comment by qingmei2** [comment]
onView 方法实际上是通过静态导包的一个方法，你可以尝试一下

![image](https://user-images.githubusercontent.com/21142152/44068769-66c28154-9fae-11e8-84aa-465fe0cc40c9.png)

**Comment by djh2717** [comment]
@qingmei2 感谢您的答复,我按照你说的试了下,的确是这样的,不知道为什么这个包不会自动导入也不会自动补全,不过问题还是解决了,谢谢!! 我申请了加群

**Comment by qingmei2** [comment]
@djh2717 好的，问题解决了就好，那我就关闭issue了 😄
