### ISSUE TITLE
kotlin语言还没有在圈子里面非常普及，作者为什么选择kotlin语言编写？

### ISSUE THREAD

**Issue by Jason-Aries** [qingmei2/RxImagePicker#35]
如题

**Comment by qingmei2** [comment]
@Jason-Aries 

准确来讲，是 **国内普及率不高**。

在今年的google开发者大会上，google官方已经宣布Kotlin在Android开发者中的使用率已达到 40%，要知道今年年初的IO大会上，使用率才30%，可见Kotlin的发展速度已经是突飞猛进。

无论是 Android 最新的官方文档，还是国外各大技术平台的技术博客，代码的示例语言已经清一色是Kotlin，我有理由认为Kotlin已经是**主流语言**（直白点吧，国外早已经烂大街了，国内的kotlin社区也已经很成熟稳定了） ，因此我也选择使用Kotlin。

有人认为无论是Kotlin还是Java，终究都只是服务于业务的工具而已，我认同这个观点，相比上班时公司项目的Java，我更喜欢Kotlin，它简洁清晰，除了语法糖，还能让我加深对函数式编程的理解。

**Comment by qingmei2** [comment]
其实这个库在开始是用Java写的，后来版本我才重构成了Kotlin版本的，我很喜欢尝试比较新的技术概念，希望你也能喜欢～ @Jason-Aries  😄

**Comment by Jason-Aries** [comment]
kotlin这个语言我也比较喜欢，的确在国内的普及率不高，特别是在多人项目的情况下，好多人都不会想去改变我们的编程习惯和学新的语法，我觉得在大环境里这个一时半刻难以改变，其实scala这个也不错的

**Comment by qingmei2** [comment]
@Jason-Aries 

👍  赞同你的观点，曾经的同事也向我推荐学习 `Scala` ，我也对这门语言很感兴趣，但是因为个人能力有限，还是准备先花一些时间沉淀自己，夯实基础后再尝试“入坑” `Scala` 。

> 好多人都不会想去改变我们的编程习惯和学新的语法

这句话真的让我感触颇深，我在自己的博客中对代码的叙述渐渐开始用 `Kotlin`，但是很多读者看到后，都对我的行为表示不理解，甚至还有直接回复：

> 一看是kotlin写的就不想看下去了。

每一门新技术或者语言，包括关于技术的探讨（比如这个issue的讨论）对于我来讲都是思想的碰撞，这对我个人的技术发展来讲是大大有益的，希望以后多多交流 ：) 🤝

**Comment by Jason-Aries** [comment]
我非常赞赏作者的多做一些开源的支持，时代在进步，语言也在进步更新，我们就需要不断的学习和创新，感谢作者做出的努力！🤝
