### ISSUE TITLE
依赖系统的库，怎么选择视频

### ISSUE THREAD

**Issue by gitzgq** [qingmei2/RxImagePicker#39]
implementation 'com.github.qingmei2:rximagepicker:2.2.0' ，这种依赖  怎么选择视频

**Comment by qingmei2** [comment]
#36

**Comment by qingmei2** [comment]
目前还不支持系统相册选择视频，后续可以考虑追加API.

**Comment by gitzgq** [comment]
好的

**Comment by qingmei2** [comment]
@gitzgq

最新的2.4.1版本已经提供了对应的API，see [detail](https://github.com/qingmei2/RxImagePicker/blob/2.x/sample/src/main/java/com/qingmei2/sample/system/SystemActivity.kt).

我会尽快更新对应的文档.
