### ISSUE TITLE
微信 加入了预览编辑功能，是否考虑加入呢

### ISSUE THREAD

**Issue by tianshaokai** [qingmei2/RxImagePicker#4]
1. 加入了预览编辑功能 贴标签 贴标签 文字 打码 和裁剪功能
2. 我看图片还有可选择原图选项，能不能实现这个功能呢？

**Comment by qingmei2** [comment]
您好，感谢您宝贵的建议:thumbsup:！

### 1.加入了预览编辑功能 贴标签 贴标签 文字 打码 和裁剪功能

这是一个很棒的提议。

**图片的编辑、剪裁、涂鸦等（后统称为图片编辑）** 是一个我可能会加入的功能，但至少不是现在。

**图像处理** 是一个很庞大的系统，并非所有的需求都需要它，即使有，也可能只是其中的一小部分。

请参考 #1 

RxImagePicker的定义很纯粹，我不希望它负载其他的责任。如果有机会，我会考虑再实现一个 RxImageEditor 诸如此类的 **图片编辑库**，并且提供和RxImagePicker对接的接口，但是这太遥远了。

### 2.可选择原图选项，能不能实现这个功能呢

从设计的角度来讲，我将您的提议理解为增加图片的 **压缩** 配置的可选项。

对于RxImagePicker来说，返回的Uri对应的文件就是对应 **图片原图**，默认的，您可以在subscribe()的方法中，对图片选择是否 进行**压缩**，然后进行对应的处理，已达到对应的目的。

我相信微信的 【原图】 选项也应该是对图片文件添加了一个临时的 **标记**,当向服务器发射数据时，根据标记做出是否压缩图片的行为。

目前RxImagePicker返回值的三种类型并未包装ExtraData，这是一个值得优化的地方，我会认真考虑的。

当然，如果您对此感兴趣，欢迎您贡献代码并提交PR 😄 。
