### ISSUE TITLE
rximagepicker:2.2.0的混淆怎么配置啊，大神

### ISSUE THREAD

**Issue by gitzgq** [qingmei2/RxImagePicker#40]
混淆怎么写啊？

**Comment by qingmei2** [comment]
@gitzgq 

不好意思，这个忘记添加了 😂 

> -keep class com.qingmei2.rximagepicker.**{*;}

我测试了一下是没有问题的，你试试呢，稍后我会更新在README中

**Comment by gitzgq** [comment]
@qingmei2   哈哈，我当时比较着急，也是这样写的，确实可以

**Comment by qingmei2** [comment]
@gitzgq 

非常谢谢你的反馈 😺 

如果没问题，我就关闭issue了哈

**Comment by gitzgq** [comment]
@qingmei2   ok
