### ISSUE TITLE
2.2.0重写知乎UI后崩溃

### ISSUE THREAD

**Issue by renjinzhi** [qingmei2/RxImagePicker#44]
重写知乎UI并放入fragment中出现闪退，闪退代码
mAdapter = AlbumMediaAdapter(
                context!!,
                mSelectionProvider!!.provideSelectedItemCollection(),
                mRecyclerView
        ).apply {
            registerCheckStateListener(this@ZhihuImageListGridFragment)
            registerOnMediaClickListener(this@ZhihuImageListGridFragment)
        }

![image](https://user-images.githubusercontent.com/26784939/52893898-516a5500-31dc-11e9-8ac0-43e7588c8a49.png)

**Comment by qingmei2** [comment]
唔，重写成什么样的代码了呢，看起来错误提示已经很明确了

**Comment by renjinzhi** [comment]
![image](https://user-images.githubusercontent.com/26784939/52895373-779bef00-31f4-11e9-9cbb-ef3d4d44c3af.png)
![image](https://user-images.githubusercontent.com/26784939/52895379-884c6500-31f4-11e9-802b-34398262fab3.png)
是在启动的时候出现的错误，UI还没有改动

**Comment by qingmei2** [comment]
应该和代码无关哈，应该是资源没有完全配置，仔细检查一下呢？

```kotlin
open class AlbumMediaAdapter():MediaGrid.OnMediaGridClickListener {

    init {
        val ta = context.theme.obtainStyledAttributes(intArrayOf(R.attr.item_placeholder))
        // 这行代码是报错的原因
        mPlaceholder = ta.getDrawable(0)
        ta.recycle()
    }
    // ....
}
```

相关配置请参考[相关资源文件](https://github.com/qingmei2/RxImagePicker/tree/2.x/rximagepicker_support_zhihu/src/main/res/values)

**Comment by qingmei2** [comment]
@renjinzhi 

如果没有什么问题，我先关闭issue了，相关疑问请重新提issue哈
