### ISSUE TITLE
qq

### ISSUE THREAD

**Issue by CPLASF1925** [qingmei2/RxImagePicker#45]
qq那个页面如何实现

**Comment by qingmei2** [comment]
@CPLASF1925 

首先需要实现一个Fragment（对应QQ式样的弹窗UI），并实现ICustomPickerView接口

然后将这个Fragment的Class交给@Gallery 注解，并声明为openAsFragment= true,并将你的容器id配置进去：

```kotlin
@Gallery(componentClazz = YourQQFragment::class,
            openAsFragment = true,
            containerViewId = R.id.frameLayout
)
    fun openGalleryAsDracula(context: Context,
                             config: ICustomPickerConfiguration): Observable<Result>
```

最后照常使用RxImagePicker即可.

详情请参考 **底层源码** 以及 [进阶使用说明](https://github.com/qingmei2/RxImagePicker/wiki/%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8#2)

**Comment by CPLASF1925** [comment]
@Gallery 只有两个参数 viewKey和containerViewId是哪的问题




From: qingmei2
Date: 2019-02-21 14:29
To: qingmei2/RxImagePicker
CC: Jacky; Mention
Subject: Re: [qingmei2/RxImagePicker] qq (#45)
@CPLASF1925
首先需要实现一个Fragment（对应QQ式样的弹窗UI），并实现ICustomPickerView接口
然后将这个Fragment的Class交给@gallery 注解，并声明为openAsFragment= true,并将你的容器id配置进去：
@Gallery(componentClazz = YourQQFragment::class,
            openAsFragment = true,
            containerViewId = R.id.frameLayout
)
    fun openGalleryAsDracula(context: Context,
                             config: ICustomPickerConfiguration): Observable<Result>
最后照常使用RxImagePicker即可.

**Comment by qingmei2** [comment]
@CPLASF1925 

下面是该注解的源码，是3个参数哈。
```Kotlin
/**
 * This annotation will be marked open Gallery，it will conflict with [Camera]
 */
@Retention
@Target(
        AnnotationTarget.FUNCTION,
        AnnotationTarget.PROPERTY_GETTER,
        AnnotationTarget.PROPERTY_SETTER
)
annotation class Gallery(

        /**
         * the UI component that will be displayed.
         */
        val componentClazz: KClass<*> = BasicGalleryFragment::class,

        /**
         * the UI component type, as [Fragment] or [Activity].
         *
         * If you use custom UI component by [Activity], then set this value false.
         */
        val openAsFragment: Boolean = true,

        /**
         * the [Fragment] container
         */
        @IdRes val containerViewId: Int = 0
)
```

如果是高度自定义的UI，建议先看源码，把库本身的实现原理搞懂哈，否则会很痛苦

**Comment by CPLASF1925** [comment]
LayoutInflater加载布局里的viewgroup id赋给containerViewId，提示找不到，是哪的问题。 










From: qingmei2
Date: 2019-02-21 14:29
To: qingmei2/RxImagePicker
CC: Jacky; Mention
Subject: Re: [qingmei2/RxImagePicker] qq (#45)
@CPLASF1925
首先需要实现一个Fragment（对应QQ式样的弹窗UI），并实现ICustomPickerView接口
然后将这个Fragment的Class交给@gallery 注解，并声明为openAsFragment= true,并将你的容器id配置进去：
@Gallery(componentClazz = YourQQFragment::class,
            openAsFragment = true,
            containerViewId = R.id.frameLayout
)
    fun openGalleryAsDracula(context: Context,
                             config: ICustomPickerConfiguration): Observable<Result>
最后照常使用RxImagePicker即可.

**Comment by qingmei2** [comment]
@CPLASF1925 

> LayoutInflater加载布局里的viewgroup id赋给containerViewId，提示找不到，是哪的问题。

containerViewId是指您要将Fragment展示到的布局容器的id（即，你要将这个局部的图片选择器展示在Activity的哪个ViewGroup中），不是Fragment内部onCreateView中的布局id哈。

根据您提示有限的信息，我可能无法帮您定位错误并提出解决方案，如果有更多疑问，请先阅读参考[How-To-Ask-Questions-The-Smart-Way](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)哈。

🤝
