### ISSUE TITLE
Camera doesn't fire when `onActivityResult` overridden 

### ISSUE THREAD

**Issue by hayahyts** [qingmei2/RxImagePicker#49]
Camera doesn't fire when `onActivityResult` overridden

**Comment by qingmei2** [comment]
@hayahyts 

The `RxImagePicker` get an invisible Fragment instance and proxy the `Activity.startActivityForResult ()`method in principle.

so don't remove this line in the `Activity` like this:

```Kotlin
// Activity....
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
    // don't remove this line:
    super.onActivityResult(requestCode, resultCode, data)
    
    //...do something if you override it.
}
```

Can this solve your issue? or you can try to describe your problem in detail. :)
