### ISSUE TITLE
我所有库都加了或者只加核心库和微信界面样式的库，但是在写到subscribe里面的Consumer时会报错，我是新建的一个项目

### ISSUE THREAD

**Issue by androidjanuary** [qingmei2/RxImagePicker#5]

**Comment by qingmei2** [comment]
您好，感谢使用RxImagePicker！

您的描述我不是确定，但是我个人猜测是否我的sample中的部分语法让您感到了困惑。

![image](https://user-images.githubusercontent.com/21142152/40537003-5bd46940-6040-11e8-93fc-dc830d8262bf.png)

如果是this::onPickUriSuccess这行代码的话，请参考Java8 **方法引用** 以及**lambda表达式** 的使用方式。

如果您是仿照我的demo的话，请检查您module下的build.gradle是否配置了Java8：

![image](https://user-images.githubusercontent.com/21142152/40537088-9d1ee394-6040-11e8-8c19-63b9e5eaa17a.png)


若没有，请添加后，重新编译。
```groovy 
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
}
```

如果我的理解有所偏差，请仔细描述您的错误，或者通过截图、代码复制的方式留言，我将第一时间回复。:smile:

**Comment by qingmei2** [comment]
@androidjanuary 

补充，您可以参考下面的wiki：

[使用微信主题UI](https://github.com/qingmei2/RxImagePicker/wiki/%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8#1.2)

**Comment by qingmei2** [comment]
@androidjanuary 

如果没有其它问题的话，我就先关闭issue了 😃
