### ISSUE TITLE
选择相册的弹框中图片有时不显示

### ISSUE THREAD

**Issue by vastyang** [qingmei2/RxImagePicker#50]
你好，我在跑sample时发现一个奇怪的问题，像图中的ListPopupWindow的单个条目图片经常加载不出来，但是首次点击可以加载出来，自己断点调试发现相应的AlbumsAdapter.bindView()和ZhihuGlideEngine.loadThumbnail()的方法都走了，希望能给我解惑，这个问题是怎么导致的，感谢。
![1554889164696](https://user-images.githubusercontent.com/19278104/55868703-98ab0b80-5bb7-11e9-9fac-547c9ec83e70.jpg)

**Comment by qingmei2** [comment]
@vastyang 

收到，这个是matisse老版本也存在的问题，我会尝试尽快解决它。

**Comment by qingmei2** [comment]
@vastyang 

bug已修复，具体修改请参考提交日志，bug修复后版本号2.4.3

感谢你的反馈～  :handshake:
