### ISSUE TITLE
我想问下demo有没有用java写的

### ISSUE THREAD

**Issue by CaiJinFu** [qingmei2/RxImagePicker#51]
我的项目都是java写的 有没有用java写的demo呢

**Comment by qingmei2** [comment]
@CaiJingFu 

你好，wiki中已经提供了Java的实现方式，请参考 [这里](https://github.com/qingmei2/RxImagePicker/wiki/%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8#12-%E4%BD%BF%E7%94%A8%E5%BE%AE%E4%BF%A1%E4%B8%BB%E9%A2%98ui)
