### ISSUE TITLE
复制微信图片选择的代码，一直提示找不到包？

### ISSUE THREAD

**Issue by CaiJinFu** [qingmei2/RxImagePicker#52]
我将demo中微信图片选择的库中的代码全部复制到我的项目中，我项目是用Java写的，但是引用的时候没有问题，编译可以通过，就是在运行的时候，提示找不到。比如RxImagePickerWechatThemeLibraryGlideModule这个类，调用的时候编译可以通过，但是运行起来就会报错。错误: 找不到符号
符号:   类 RxImagePickerWechatThemeLibraryGlideModule
位置: 类 MainActivity
怎么解决？

**Comment by qingmei2** [comment]
@CaiJingFu 

你同时开了2个issue，我先把关闭这个了
