### ISSUE TITLE
通过openCamera打开相机拍照后没有接收到数据，onNext、onError、onComplete都没有执行

### ISSUE THREAD

**Issue by solartcc** [qingmei2/RxImagePicker#54]
通过openCamera打开相机拍照后没有接收到数据，onNext、onError、onComplete都没有执行，但是通过openGallery中的相机拍摄照片有返回，我还不能定位问题，劳烦您帮忙看看，感谢！

**Comment by qingmei2** [comment]
@solartcc 

你是不是重写Activity的onActivityResult方法了呢？

因为你提供的信息过少，我无法给出准确的方案，请尝试运行demo，看看demo能否成功取到照片，如果可以则不是特殊机型的问题。

**Comment by solartcc** [comment]
是的，重写了onActivityResult，处理后没问题了，感谢！

**Comment by qingmei2** [comment]
@solartcc 

那我就关闭issue 了哈。 🤝
