### ISSUE TITLE
相册选中BUG

### ISSUE THREAD

**Issue by diao-jian** [qingmei2/RxImagePicker#55]
相册中连续点击同一张图片会崩溃

java.lang.IllegalStateException: cursor.getString(cursor.….MediaColumns.MIME_TYPE)) must not be null

**Comment by qingmei2** [comment]
@diao-jian 

收到，我会尽快调查崩溃原因

**Comment by qingmei2** [comment]
@diao-jian 

你好，能否提供更多的信息呢，目前该问题我还没有复现到

* 崩溃发生的主题
* 图片选择相关的代码

这些都能帮助我尽快定位到问题，谢谢！

**Comment by qingmei2** [comment]
无法重现该bug, 如果有遇到该问题的朋友，请在该issue下进行描述，我将持续关注该问题

**Comment by diao-jian** [comment]
不好意思哈，这一段时间有点忙，空了再看看



------------------ 原始邮件 ------------------
发件人: "qingmei2"<notifications@github.com>; 
发送时间: 2019年6月5日(星期三) 中午11:42
收件人: "qingmei2/RxImagePicker"<RxImagePicker@noreply.github.com>; 
抄送: "梅吟怀"<554256686@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [qingmei2/RxImagePicker] 相册选中BUG (#55)




Closed #55.

**Comment by qingmei2** [comment]
该bug再次复现，合并处理。
