### ISSUE TITLE
自己项目中导入glide最新版本，会崩溃!

### ISSUE THREAD

**Issue by OwnerKobe** [qingmei2/RxImagePicker#56]

**Comment by OwnerKobe** [comment]
具体崩溃原因-at com.qingmei2.rximagepicker_extension_wechat.engine.impl.WechatGlideEngine.loadThumbnail。

**Comment by qingmei2** [comment]
请尝试创建属于您项目版本的GlideEngine呢？具体实现参考源码的实现即可

**Comment by OwnerKobe** [comment]
自己写了个类继承ImageEngine， 代码跟你写的WechatGlideEngine一模一样，使用自己写的然后就不崩溃了。不明白这是为啥。。 大神能解惑吗？

**Comment by qingmei2** [comment]
Glide版本不同的问题，库依赖的版本是4.8，可能会和最新的版本有冲突。

没问题的话我就关闭了哈
