### ISSUE TITLE
Glide、主题的bug

### ISSUE THREAD

**Issue by HZHAndroid** [qingmei2/RxImagePicker#58]
需要手动加入Glid库，知乎和微信主题打开都黑屏。而且会弹出无响应的弹出框。

**Comment by qingmei2** [comment]
@HZHAndroid 

能否叙述更详细一些呢？

> 知乎和微信主题打开都黑屏。而且会弹出无响应的弹出框。

库目前为止已经有很多开发者集成到商业项目中了，你尝试运行demo了吗，是否可以正常运行？

> 需要手动加入Glide库

库默认没有依赖任何图片加载的库，所以开发者需要自行依赖，请参考wiki进行对应的配置
