### ISSUE TITLE
大佬帮忙看看  报错

### ISSUE THREAD

**Issue by anzhuojinjie** [qingmei2/RxImagePicker#59]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.joey.loanmarket/com.qingmei2.rximagepicker_extension_zhihu.ui.ZhihuImagePickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.lifecycle.Lifecycle$State androidx.lifecycle.Lifecycle.getCurrentState()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2514)

用微信或者知乎的主题打开相册都会报这个错，打开系统相册没有问题

**Comment by qingmei2** [comment]
@anzhuojinjie 

你的依赖库版本多少，项目本身迁移AndroidX了吗？请尝试fork这个项目并尝试运行demo，看看demo能否成功运行呢

请尽量描述你项目中的环境配置，方便我更快定位到错误的原因。 :handshake:
