### ISSUE TITLE
如何判断选择的是图片还是视频格式呢

### ISSUE THREAD

**Issue by azheng95** [qingmei2/RxImagePicker#61]
原库Matisse 可根据选择后的后缀格式进行判断 比如 123.jpg
但是这个库，并没有带格式的后缀了 123

**Comment by azheng95** [comment]
现在用RxImagePicker 里知乎的ui 从返回的t.uri 里判断是否包含 images  或 video，来判断是否是图片还是视频，不知道这种方法会不会有问题

**Comment by qingmei2** [comment]
@RookieExaminer 

可以考虑为知乎和微信主题的返回结果，增加对应的字段以告知媒体资源的类型（视频、图片、音频），该功能预计会在下版本更新

**Comment by qingmei2** [comment]
@RookieExaminer 

该功能2.5.0版本更新，**知乎** 和 **微信** 主题增加了返回 **资源文件类型** 的字段：

#### 代码示例：

```kotlin
val mimeType = result.getStringExtra("EXTRA_OPTIONAL_MIME_TYPE", "")
Log.d(TAG, "mime types: $mimeType")
```

![](https://user-images.githubusercontent.com/21142152/59154271-25335680-8aa1-11e9-9b96-f6c987fa5fb9.png)

#### 使用方式参考类似代码：

```
val isImage: Boolean
      get() = if (mimeType == null) false else mimeType == MimeType.JPEG.toString()
           || mimeType == MimeType.PNG.toString()
           || mimeType == MimeType.GIF.toString()
           || mimeType == MimeType.BMP.toString()
           || mimeType == MimeType.WEBP.toString()
```
