### ISSUE TITLE
SystemImagePicker 无法创建:不能从静态上下文引用非静态“create（）”

### ISSUE THREAD

**Issue by zihang740** [qingmei2/RxImagePicker#62]
在Activity--->onCreate中--->RxImagePicker.create(),create()报错,''Non-static 'create()' cannot be referenced from a static context''无法创建:不能从静态上下文引用非静态“create（）”,引入    api "com.github.qingmei2:rximagepicker:2.2.0",{
        exclude group: 'com.android.support', module: 'appcompat-v7'
        exclude group: 'com.android.support', module: 'recyclerview-v7'
    }

**Comment by qingmei2** [comment]
@zihang740 

该接口在2.4.1版本之后才提供，请参考 [2.4.1更新文档](https://github.com/qingmei2/RxImagePicker/releases/tag/2.4.1)

2.2.0版本请使用如下方式：

> RxImagePicker.INSTANCE.create(XXX.class);  // 先获取静态实例
