### ISSUE TITLE
修复#55的2.X版本多久才才可以出来呀？

### ISSUE THREAD

**Issue by diswy** [qingmei2/RxImagePicker#69]
之前见作者修复了 #55  的问题，请问2.x 的最新版本号是多少？2.5.0 偶尔会出现那个问题

**Comment by qingmei2** [comment]
最近比较忙，代码已经合并了，这两天尽快发布

**Comment by qingmei2** [comment]
@diswy 

请尝试依赖 2.5.1版本

https://github.com/qingmei2/RxImagePicker/releases/tag/2.5.1

此外，收到您的反馈，我会将2.x版本和3.x版本的版本号都在首页展示供开发者查阅。
