### ISSUE TITLE
androidx和rx的问题

### ISSUE THREAD

**Issue by AndMy** [qingmei2/RxImagePicker#71]
androidx和rx的问题
项目已近迁移到androidx，但是rx没有到3.x就不能使用了？

**Comment by qingmei2** [comment]
@AndMy 

是可以的，参考wiki文档，请直接使用 `2.5.1`即可

![image](https://user-images.githubusercontent.com/21142152/63324809-6d9da900-c35b-11e9-8a82-fc53b61b84cf.png)
