### ISSUE TITLE
返回的图片Uri是图片的媒体库Uri,建议加上文件的实际路径 根据需求自主选择更好

### ISSUE THREAD

**Issue by JM-Jackson** [qingmei2/RxImagePicker#72]
今天遇到一个需求，如果我要去判断这个图片地址是否存在,通过uri 判断到的永远是空的，会造成一些业务上面的不兼容，建议作者加上一个绝对路径比较好

**Comment by nEdAy** [comment]
我也遇到了这个问题，部分手机从相册获取，拿到的URI
Unable to decode stream: java.io.FileNotFoundException: /-1/1/content:/media/external/images/media/53898/ORIGINAL/NONE/837250474: open failed: ENOENT (No such file or directory)

**Comment by nEdAy** [comment]
MIUI 10正常 Pixel2 XL Android10异常

**Comment by nEdAy** [comment]
是兼容Google相册的问题，路径格式如下：
content://com.google.android.apps.photos.contentprovider/0/1/mediakey%3A%2Flocal%253A821abd2f-9f8c-4931-bbe9-a975d1f5fabc/ORIGINAL/NONE/1754758324

**Comment by nEdAy** [comment]
使用了这位老哥的代码 解决了 https://github.com/xiangshiweiyu/PicTest/blob/master/app/src/main/java/com/example/hxd/pictest/getPhotoFromPhotoAlbum.java

**Comment by qingmei2** [comment]
@nEdAy 

感谢你提供的解决方案！ :smile:

**Comment by qingmei2** [comment]
我目前可能不会优先考虑增加太多的API，而是尽量朝Android原生靠拢。

是否有严格的必要增加这样一个API呢（或者考虑添加对应的一个工具类，方便开发者调用）？

> 获取文件的实际路径

**Comment by JM-Jackson** [comment]
如果API不增加，那么添加一个对应的工具类，让开发者自由调用, 这个方案完全可以。
> 我目前可能不会优先考虑增加太多的API，否则至少朝Android原生靠拢。
> 
> 是否有严格的必要增加这样一个API呢（或考虑添加对应的一个工具类，方便开发者调用）？

**Comment by qingmei2** [comment]
考虑到Android10的影响:

> 自Android Q开始，公有目录File API都失效，不能直接通过new File(path).exists();判断公有目录文件是否存在。

因此统一使用Uri，用户可以考虑自己使用额外Uri相关的Utils进行转换。

以返回图片Uri  存储本地临时 cacheDir 目录为例：

```Kotlin
// 1.获取 contentResolver
val resolver = appContext.contentResolver
// 2.通过Uri解析Bimap
val picture: Bitmap = BitmapFactory.decodeStream(resolver.openInputStream(imageUri))
// 3.将Bitmap存入指定目录下（CacheDir）,并返回临时文件的Uri
val localPictureUri = writeBitmapToFile(appContext, picture)

fun writeBitmapToFile(applicationContext: Context, bitmap: Bitmap): Uri {
    val name = String.format("bitmap-output-%s.png", UUID.randomUUID().toString())
    val outputDir = File(applicationContext.filesDir, "bitmap_output")
    if (!outputDir.exists()) {
        outputDir.mkdirs() // should succeed
    }
    val outputFile = File(outputDir, name)
    var out: FileOutputStream? = null
    try {
        out = FileOutputStream(outputFile)
        bitmap.compress(Bitmap.CompressFormat.PNG, 0 /* ignored for PNG */, out)
    } finally {
        out?.let {
            try {
                it.close()
            } catch (ignore: IOException) {
            }

        }
    }
    return Uri.fromFile(outputFile)
}
```
