### ISSUE TITLE
Supplier这个接口，好像Rxjava2跟Rxjava3路径不一样了

### ISSUE THREAD

**Issue by ultraman521** [qingmei2/RxImagePicker#73]
![Uploading image.png…]()
我用的是：io.reactivex.rxjava3:rxjava:3.0.0-RC4

调用 `RxImagePicker
         .create(MyImagePicker.class)
         .openGallery(this)`就会报错Failed resolution of: Lio/reactivex/functions/Supplier;

**Comment by ultraman521** [comment]
换成io.reactivex.rxjava3:rxjava:3.0.0-RC0就好了

**Comment by qingmei2** [comment]
@ultraman521 收到，我会尽快检查这个问题，保证库能够兼容Rx的最新版本

**Comment by qingmei2** [comment]
@ultraman521 

新版本已经提供了rxjava3的兼容
