### ISSUE TITLE
2.5.1知乎主题选择多张图片怎么返回List

### ISSUE THREAD

**Issue by gitzgq** [qingmei2/RxImagePicker#78]
2.5.1知乎主题选择多张图片怎么返回List？

**Comment by qingmei2** [comment]
@gitzgq 

使用 `Observable<T>.toList()` 函数可以吗？

类似 #14

**Comment by gitzgq** [comment]
如下写法是可以的，感谢大神；但是有个问题，进入到相册不选择任何照片，直接返回也会走成功的回调 返回的集合是空的，使用起来不会有影响，做个判断就行
imagePicker?.openMoreAlbum(it,
                    ZhihuConfigurationBuilder(MimeType.ofImage(), false)
                        .maxSelectable(maxSize)
                        .spanCount(3)
                        .countable(true)
                        .theme(R.style.Zhihu_Dracula)
                        .build())
                    ?.toList()
                    ?.subscribe(
                        Consumer<List<Result>> { t ->
                            ZLog.e("图片个数 = ${t.size}")
                        },
                        Consumer<Throwable> { imgCallBack.onFinish("") })

**Comment by qingmei2** [comment]
@gitzgq 

因为`Observable<T>.toList()`操作符返回的是一个`Single`类型，这意味着，流中的数据元素数量有且仅能为1，当没有数据元素或者超出1时则会抛出异常被`onError`捕获，如果抛出异常的话，则与我们的预期不符（因为我们库中源码调用的是`onComplete()`——虽然没有数据的返回）。

因此`toList()`返回一个空的集合的设计是有道理的（而且是`RxJava`内部处理的，我无法修改它）

对此你可以参考`ObservableToListSingle`类：

```Java
static final class ToListObserver<T, U extends Collection<? super T>> implements Observer<T>, Disposable {
        //...
        U collection;
       
         @Override
        public void onNext(T t) {
            collection.add(t);
        }

        @Override
        public void onComplete() {
            U c = collection;
            collection = null;
            // 当我们调用onComplete时候，直接返回集合，若集合没有数据，则是空列表.
            downstream.onSuccess(c);
        }
}
```

**Comment by gitzgq** [comment]
嗯，OK，感谢
