### ISSUE TITLE
知乎主题图片选择器崩溃

### ISSUE THREAD

**Issue by Roben1016** [qingmei2/RxImagePicker#85]
最近在bugly上看到几个崩溃, 提示是RxImagePicker带来的, 使用的版本是2.5.2
以下是日志截图
![RxImagePicker崩溃1](https://user-images.githubusercontent.com/15700182/79448594-409db500-8014-11ea-8d2b-fd7f992dc2c1.png)

![RxImagePicker崩溃手机型号](https://user-images.githubusercontent.com/15700182/79448608-47c4c300-8014-11ea-91f9-72d5cc93d4f3.png)

**Comment by Roben1016** [comment]
不知道图片上传成功没,我再复制下文字
#11704 kotlin.KotlinNullPointerException
com.qingmei2.rximagepicker_extension.model.SelectedItemCollection.onCreate(SelectedItemCollection.kt:55)
com.qingmei2.rximagepicker_extension.model.SelectedItemCollection.onCreate(SelectedItemCollection.kt:55)
--
2 com.qingmei2.rximagepicker_extension_zhihu.ui.ZhihuImagePickerFragment.onViewCreated(ZhihuImagePickerFragment.kt:76)
3 androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:892)
4 androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
5 androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
6 androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
7 androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
8 androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
9 androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
10 androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
11 android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
12 android.app.Activity.performStart(Activity.java:7275)
13 android.app.ActivityThread.handleStartActivity(ActivityThread.java:3181)


然后下面是部分崩溃的手机型号和版本号

VIVO V1831A     Android 9,level 28

VIVO X21I A       Android 9,level 28


华为 PAR AL00    Android 9,level 28

华为 ELE AL00    Android 10,level 29

**Comment by diswy** [comment]
同样问题，不知道作者现在还维护么

**Comment by qingmei2** [comment]
@diswy 
@Roben1016 

复现原因： 屏幕旋转重建Fragment时导致的问题，已修复。

请尝试依赖2.5.4版本。

**Comment by Roben1016** [comment]
好的，谢谢大佬
